FILES = \
	arith4.xhtml \
	bitwise1.xhtml \
	bitwise2.xhtml \
	bitwise3.xhtml \
	bnf1.xhtml \
	ecmascript3.xhtml \
	ecmascript5.xhtml \
	exn1.xhtml \
	exn2.xhtml \
	go1.xhtml \
	java4.xhtml \
	logic2.xhtml \
	perl5.xhtml \
	perl6.xhtml \
	prog2.xhtml \
	python2.xhtml \
	python2.xhtml \
	quant2.xhtml \
	rounding_euc.xhtml \
	ruby1.xhtml \
	sts3.xhtml \
	sts4.xhtml \
	sts5.xhtml \
	typename8.xhtml \
	typename16.xhtml \
	typename32.xhtml \
	typename64.xhtml \
	typename128.xhtml \
	typename256.xhtml \
	typename512.xhtml \
	typename1024.xhtml \
	znot1.xhtml

#	switch1.xhtml \
#	switch2.xhtml \
#	switch3.xhtml \
#	switch4.xhtml \
#	switch5.xhtml \
#	switch6.xhtml \
#	syntax1.xhtml \

all: $(FILES)
	:

%.xhtml: %.ocd
	../../static/bin/cd2xhtml.sh $<
